-- Material Consumption Detail Rows — raw events with PJ_TYPE join.
-- Truncation guard: FETCH FIRST 100001 ROWS ONLY (same as material-trace pattern).
-- {{ WHERE_CLAUSE }} is replaced by QueryBuilder.build() with parameterized conditions.

SELECT
    m.CONTAINERID          AS CONTAINERID,
    c.CONTAINERNAME        AS CONTAINERNAME,
    m.PJ_WORKORDER         AS PJ_WORKORDER,
    m.WORKCENTERNAME       AS WORKCENTERNAME,
    m.MATERIALPARTNAME     AS MATERIALPARTNAME,
    m.MATERIALLOTNAME      AS MATERIALLOTNAME,
    m.VENDORLOTNUMBER      AS VENDORLOTNUMBER,
    m.QTYREQUIRED          AS QTYREQUIRED,
    m.QTYCONSUMED          AS QTYCONSUMED,
    m.EQUIPMENTNAME        AS EQUIPMENTNAME,
    TRUNC(m.TXNDATE)       AS TXNDATE,
    m.PRIMARY_CATEGORY     AS PRIMARY_CATEGORY,
    m.SECONDARY_CATEGORY   AS SECONDARY_CATEGORY,
    c.PJ_TYPE              AS pj_type,
    TRIM(c.PRODUCTLINENAME) AS PRODUCTLINENAME
FROM DWH.DW_MES_LOTMATERIALSHISTORY m
LEFT JOIN DWH.DW_MES_CONTAINER c
    ON c.CONTAINERID = m.CONTAINERID
{{ WHERE_CLAUSE }}
ORDER BY m.TXNDATE DESC
FETCH FIRST 100001 ROWS ONLY
