-- Reject History Detail List (Paginated)
-- Template slots:
--   BASE_QUERY (base reject-history daily dataset SQL)
--   WHERE_CLAUSE (QueryBuilder-generated WHERE clause against alias b)

{{ BASE_WITH_CTE }},
filtered AS (
    SELECT
        b.*,
        COUNT(*) OVER () AS TOTAL_COUNT
    FROM base b
    {{ WHERE_CLAUSE }}
)
SELECT
    TXN_DAY,
    TXN_MONTH,
    WORKCENTER_GROUP,
    WORKCENTERSEQUENCE_GROUP,
    WORKCENTERNAME,
    SPECNAME,
    EQUIPMENTNAME,
    PRIMARY_EQUIPMENTNAME,
    PRODUCTLINENAME,
    PJ_TYPE,
    LOSSREASONNAME,
    LOSSREASON_CODE,
    REJECT_EVENT_ROWS,
    AFFECTED_LOT_COUNT,
    AFFECTED_WORKORDER_COUNT,
    MOVEIN_QTY,
    REJECT_QTY,
    REJECT_TOTAL_QTY,
    DEFECT_QTY,
    STANDBY_QTY,
    QTYTOPROCESS_QTY,
    INPROCESS_QTY,
    PROCESSED_QTY,
    REJECT_RATE_PCT,
    DEFECT_RATE_PCT,
    REJECT_SHARE_PCT,
    TOTAL_COUNT
FROM filtered
ORDER BY
    TXN_DAY DESC,
    WORKCENTERSEQUENCE_GROUP ASC,
    WORKCENTERNAME ASC,
    REJECT_TOTAL_QTY DESC
OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY
