-- Optimized: reject_history/performance_daily
-- Change: Replaced REGEXP_SUBSTR with SUBSTR/INSTR cascade for LOSSREASON_CODE
--         (REGEXP_SUBSTR per-row is ~5x slower than SUBSTR/INSTR on large datasets)
--
-- Original regex: '^[^_[:space:]-]+' extracts text before first _, space, or dash

WITH spec_map AS (
    SELECT
        SPEC,
        MIN(WORK_CENTER) KEEP (
            DENSE_RANK FIRST ORDER BY WORKCENTERSEQUENCE_GROUP
        ) AS WORK_CENTER,
        MIN(WORK_CENTER_GROUP) KEEP (
            DENSE_RANK FIRST ORDER BY WORKCENTERSEQUENCE_GROUP
        ) AS WORKCENTER_GROUP,
        MIN(WORKCENTERSEQUENCE_GROUP) AS WORKCENTERSEQUENCE_GROUP
    FROM DWH.DW_MES_SPEC_WORKCENTER_V
    WHERE SPEC IS NOT NULL
    GROUP BY SPEC
),
reject_raw AS (
    SELECT
        TRUNC(r.TXNDATE) AS TXN_DAY,
        TO_CHAR(TRUNC(r.TXNDATE), 'YYYY-MM') AS TXN_MONTH,
        r.CONTAINERID,
        TRIM(r.PJ_WORKORDER) AS PJ_WORKORDER,
        NVL(TRIM(c.PJ_TYPE), '(NA)') AS PJ_TYPE,
        NVL(TRIM(c.PRODUCTLINENAME), '(NA)') AS PRODUCTLINENAME,
        NVL(TRIM(c.OBJECTTYPE), '(NA)') AS SCRAP_OBJECTTYPE,
        NVL(TRIM(sm.WORK_CENTER), NVL(TRIM(r.WORKCENTERNAME), '(NA)')) AS WORKCENTERNAME,
        NVL(TRIM(sm.WORKCENTER_GROUP), NVL(TRIM(r.WORKCENTERNAME), '(NA)')) AS WORKCENTER_GROUP,
        NVL(sm.WORKCENTERSEQUENCE_GROUP, 999) AS WORKCENTERSEQUENCE_GROUP,
        NVL(TRIM(r.SPECNAME), '(NA)') AS SPECNAME,
        NVL(TRIM(r.EQUIPMENTNAME), '(NA)') AS EQUIPMENTNAME,
        NVL(TRIM(r.LOSSREASONNAME), '(未填寫)') AS LOSSREASONNAME,
        -- Optimized: SUBSTR/INSTR instead of REGEXP_SUBSTR
        NVL(
          TRIM(
            SUBSTR(
              NVL(TRIM(r.LOSSREASONNAME), '(未填寫)'),
              1,
              LEAST(
                CASE WHEN INSTR(NVL(TRIM(r.LOSSREASONNAME), '(未填寫)'), '_') > 0
                     THEN INSTR(NVL(TRIM(r.LOSSREASONNAME), '(未填寫)'), '_') - 1
                     ELSE LENGTH(NVL(TRIM(r.LOSSREASONNAME), '(未填寫)')) END,
                CASE WHEN INSTR(NVL(TRIM(r.LOSSREASONNAME), '(未填寫)'), ' ') > 0
                     THEN INSTR(NVL(TRIM(r.LOSSREASONNAME), '(未填寫)'), ' ') - 1
                     ELSE LENGTH(NVL(TRIM(r.LOSSREASONNAME), '(未填寫)')) END,
                CASE WHEN INSTR(NVL(TRIM(r.LOSSREASONNAME), '(未填寫)'), '-') > 0
                     THEN INSTR(NVL(TRIM(r.LOSSREASONNAME), '(未填寫)'), '-') - 1
                     ELSE LENGTH(NVL(TRIM(r.LOSSREASONNAME), '(未填寫)')) END
              )
            )
          ),
          NVL(TRIM(r.LOSSREASONNAME), '(未填寫)')
        ) AS LOSSREASON_CODE,
        NVL(r.MOVEINQTY, 0) AS MOVEINQTY,
        NVL(r.REJECTQTY, 0) AS REJECT_QTY,
        NVL(r.STANDBYQTY, 0) AS STANDBY_QTY,
        NVL(r.QTYTOPROCESS, 0) AS QTYTOPROCESS_QTY,
        NVL(r.INPROCESSQTY, 0) AS INPROCESS_QTY,
        NVL(r.PROCESSEDQTY, 0) AS PROCESSED_QTY,
        NVL(r.REJECTQTY, 0)
          + NVL(r.STANDBYQTY, 0)
          + NVL(r.QTYTOPROCESS, 0)
          + NVL(r.INPROCESSQTY, 0)
          + NVL(r.PROCESSEDQTY, 0) AS REJECT_TOTAL_QTY,
        NVL(r.DEFECTQTY, 0) AS DEFECT_QTY,
        ROW_NUMBER() OVER (
            PARTITION BY NVL(
                TRIM(r.HISTORYMAINLINEID),
                TRIM(r.CONTAINERID) || ':' || TO_CHAR(r.TXNDATE, 'YYYYMMDDHH24MISS') || ':' || NVL(TRIM(r.SPECID), '-')
            )
            ORDER BY NVL(TRIM(r.LOSSREASONNAME), ' ')
        ) AS EVENT_RN
    FROM DWH.DW_MES_LOTREJECTHISTORY r
    LEFT JOIN DWH.DW_MES_CONTAINER c
      ON c.CONTAINERID = r.CONTAINERID
    LEFT JOIN spec_map sm
      ON sm.SPEC = TRIM(r.SPECNAME)
    WHERE {{ BASE_WHERE }}
),
daily_agg AS (
    SELECT
        TXN_DAY,
        TXN_MONTH,
        WORKCENTER_GROUP,
        WORKCENTERSEQUENCE_GROUP,
        WORKCENTERNAME,
        SPECNAME,
        EQUIPMENTNAME,
        PRODUCTLINENAME,
        SCRAP_OBJECTTYPE,
        PJ_TYPE,
        LOSSREASONNAME,
        LOSSREASON_CODE,
        COUNT(DISTINCT CONTAINERID) AS AFFECTED_LOT_COUNT,
        COUNT(DISTINCT PJ_WORKORDER) AS AFFECTED_WORKORDER_COUNT,
        SUM(CASE WHEN EVENT_RN = 1 THEN MOVEINQTY ELSE 0 END) AS MOVEIN_QTY,
        SUM(REJECT_QTY) AS REJECT_QTY,
        SUM(REJECT_TOTAL_QTY) AS REJECT_TOTAL_QTY,
        SUM(DEFECT_QTY) AS DEFECT_QTY,
        SUM(STANDBY_QTY) AS STANDBY_QTY,
        SUM(QTYTOPROCESS_QTY) AS QTYTOPROCESS_QTY,
        SUM(INPROCESS_QTY) AS INPROCESS_QTY,
        SUM(PROCESSED_QTY) AS PROCESSED_QTY
    FROM reject_raw
    GROUP BY
        TXN_DAY,
        TXN_MONTH,
        WORKCENTER_GROUP,
        WORKCENTERSEQUENCE_GROUP,
        WORKCENTERNAME,
        SPECNAME,
        EQUIPMENTNAME,
        PRODUCTLINENAME,
        SCRAP_OBJECTTYPE,
        PJ_TYPE,
        LOSSREASONNAME,
        LOSSREASON_CODE
)
SELECT
    TXN_DAY,
    TXN_MONTH,
    WORKCENTER_GROUP,
    WORKCENTERSEQUENCE_GROUP,
    WORKCENTERNAME,
    SPECNAME,
    EQUIPMENTNAME,
    PRODUCTLINENAME,
    SCRAP_OBJECTTYPE,
    PJ_TYPE,
    LOSSREASONNAME,
    LOSSREASON_CODE,
    AFFECTED_LOT_COUNT,
    AFFECTED_WORKORDER_COUNT,
    MOVEIN_QTY,
    REJECT_QTY,
    REJECT_TOTAL_QTY,
    DEFECT_QTY,
    STANDBY_QTY,
    QTYTOPROCESS_QTY,
    INPROCESS_QTY,
    PROCESSED_QTY,
    CASE
        WHEN MOVEIN_QTY = 0 THEN 0
        ELSE ROUND(REJECT_TOTAL_QTY * 100 / MOVEIN_QTY, 4)
    END AS REJECT_RATE_PCT,
    CASE
        WHEN MOVEIN_QTY = 0 THEN 0
        ELSE ROUND(DEFECT_QTY * 100 / MOVEIN_QTY, 4)
    END AS DEFECT_RATE_PCT,
    CASE
        WHEN (REJECT_TOTAL_QTY + DEFECT_QTY) = 0 THEN 0
        ELSE ROUND(REJECT_TOTAL_QTY * 100 / (REJECT_TOTAL_QTY + DEFECT_QTY), 4)
    END AS REJECT_SHARE_PCT
FROM daily_agg
