-- Forward Material Trace by Work Order (PJ_WORKORDER)
-- Retrieves material consumption records for given work orders
--
-- Parameters:
--   Bind variables generated by QueryBuilder.add_in_condition()
--   for PJ_WORKORDER IN (p0, p1, ...)
--
-- Template slots:
--   {{ WHERE_CLAUSE }} - Dynamic WHERE with PJ_WORKORDER IN + optional WORKCENTERNAME IN

SELECT
    m.CONTAINERID,
    c.CONTAINERNAME,
    m.PJ_WORKORDER,
    m.WORKCENTERNAME,
    m.MATERIALPARTNAME,
    m.MATERIALLOTNAME,
    m.VENDORLOTNUMBER,
    m.QTYREQUIRED,
    m.QTYCONSUMED,
    m.EQUIPMENTNAME,
    m.TXNDATE,
    m.PRIMARY_CATEGORY,
    m.SECONDARY_CATEGORY
FROM DWH.DW_MES_LOTMATERIALSHISTORY m
LEFT JOIN DWH.DW_MES_CONTAINER c
    ON c.CONTAINERID = m.CONTAINERID
{{ WHERE_CLAUSE }}
ORDER BY m.TXNDATE DESC
FETCH FIRST 50001 ROWS ONLY
