-- Forward Material Trace by LOT (CONTAINERID)
-- Retrieves material consumption records for given CONTAINERIDs
--
-- Parameters:
--   Bind variables generated by QueryBuilder.add_in_condition()
--   for CONTAINERID IN (:p0, :p1, ...)
--
-- Template slots:
--   {{ WHERE_CLAUSE }} - Dynamic WHERE with CONTAINERID IN + optional WORKCENTERNAME IN

SELECT
    m.CONTAINERID,
    c.CONTAINERNAME,
    m.PJ_WORKORDER,
    m.WORKCENTERNAME,
    m.MATERIALPARTNAME,
    m.MATERIALLOTNAME,
    m.VENDORLOTNUMBER,
    m.QTYREQUIRED,
    m.QTYCONSUMED,
    m.EQUIPMENTNAME,
    m.TXNDATE,
    m.PRIMARY_CATEGORY,
    m.SECONDARY_CATEGORY
FROM DWH.DW_MES_LOTMATERIALSHISTORY m
LEFT JOIN DWH.DW_MES_CONTAINER c
    ON c.CONTAINERID = m.CONTAINERID
{{ WHERE_CLAUSE }}
ORDER BY m.TXNDATE DESC
