-- Resolve CONTAINERNAME to CONTAINERID
-- Batch lookup for LOT ID -> CONTAINERID conversion
--
-- Parameters:
--   Bind variables generated by QueryBuilder.add_in_condition()
--   for CONTAINERNAME IN (p0, p1, ...)

SELECT
    c.CONTAINERID,
    c.CONTAINERNAME
FROM DWH.DW_MES_CONTAINER c
{{ WHERE_CLAUSE }}
