-- Reverse Material Trace by Material Lot Name (MATERIALLOTNAME)
-- Retrieves LOTs that consumed given material lot names
--
-- Parameters:
--   Bind variables generated by QueryBuilder.add_in_condition()
--   for MATERIALLOTNAME IN (:p0, :p1, ...)
--
-- Template slots:
--   {{ WHERE_CLAUSE }} - Dynamic WHERE with MATERIALLOTNAME IN + optional WORKCENTERNAME IN
--
-- Note: FETCH FIRST 10001 ROWS ONLY to detect truncation (> 10000)

SELECT
    m.CONTAINERID,
    c.CONTAINERNAME,
    m.PJ_WORKORDER,
    m.WORKCENTERNAME,
    m.MATERIALPARTNAME,
    m.MATERIALLOTNAME,
    m.VENDORLOTNUMBER,
    m.QTYREQUIRED,
    m.QTYCONSUMED,
    m.EQUIPMENTNAME,
    m.TXNDATE,
    m.PRIMARY_CATEGORY,
    m.SECONDARY_CATEGORY
FROM DWH.DW_MES_LOTMATERIALSHISTORY m
LEFT JOIN DWH.DW_MES_CONTAINER c
    ON c.CONTAINERID = m.CONTAINERID
{{ WHERE_CLAUSE }}
ORDER BY m.TXNDATE DESC
FETCH FIRST 10001 ROWS ONLY
