-- Equipment Lot Reject Detail Query
-- Resolves equipment IDs to lot CONTAINERID set via LOTWIPHISTORY, then returns
-- one detail row per LOTREJECTHISTORY event for those lots.
--
-- Cross-station semantic (QT-07): EQUIPMENTNAME in the result reflects the
-- reject event's equipment, which may differ from the queried equipment IDs
-- (a lot processed on Furnace-A may have its reject logged under Furnace-B).
--
-- Parameters:
--   :start_date - Start date (YYYY-MM-DD) — applied on TRACKINTIMESTAMP
--   :end_date   - End date (YYYY-MM-DD)   — applied on TRACKINTIMESTAMP
--
-- Dynamic placeholders:
--   EQUIPMENT_FILTER - IN condition on h.EQUIPMENTID from LOTWIPHISTORY
--
-- Note: LOTREJECTHISTORY has NO EQUIPMENTID — CONTAINERID is the only
--       correct join key for cross-station reject capture.
--       Uses LOSSREASONNAME (NOT REJECTREASONNAME).
--       Uses TXNDATE (NOT TXNDATETIME).
--       REJECT_TOTAL_QTY = REJECTQTY + STANDBYQTY + QTYTOPROCESS + INPROCESSQTY + PROCESSEDQTY

WITH spec_map AS (
    SELECT
        SPEC,
        MIN(WORK_CENTER) KEEP (
            DENSE_RANK FIRST ORDER BY WORKCENTERSEQUENCE_GROUP
        ) AS WORK_CENTER,
        MIN(WORK_CENTER_GROUP) KEEP (
            DENSE_RANK FIRST ORDER BY WORKCENTERSEQUENCE_GROUP
        ) AS WORKCENTER_GROUP,
        MIN(WORKCENTERSEQUENCE_GROUP) AS WORKCENTERSEQUENCE_GROUP
    FROM DWH.DW_MES_SPEC_WORKCENTER_V
    WHERE SPEC IS NOT NULL
    GROUP BY SPEC
),
wip_lots AS (
    SELECT DISTINCT h.CONTAINERID
    FROM DWH.DW_MES_LOTWIPHISTORY h
    WHERE h.TRACKINTIMESTAMP >= TO_DATE(:start_date, 'YYYY-MM-DD')
      AND h.TRACKINTIMESTAMP < TO_DATE(:end_date, 'YYYY-MM-DD') + 1
      AND h.EQUIPMENTID IS NOT NULL
      AND h.TRACKINTIMESTAMP IS NOT NULL
      AND {{ EQUIPMENT_FILTER }}
),
reject_data AS (
    SELECT
        r.CONTAINERID,
        NVL(TRIM(c.CONTAINERNAME), TRIM(r.CONTAINERID)) AS CONTAINERNAME,
        NVL(TRIM(sm.WORK_CENTER), NVL(TRIM(r.WORKCENTERNAME), '(NA)')) AS WORKCENTERNAME,
        NVL(TRIM(sm.WORKCENTER_GROUP), NVL(TRIM(r.WORKCENTERNAME), '(NA)')) AS WORKCENTER_GROUP,
        NVL(sm.WORKCENTERSEQUENCE_GROUP, 999) AS WORKCENTERSEQUENCE_GROUP,
        NVL(TRIM(c.PRODUCTLINENAME), '(NA)') AS PRODUCTLINENAME,
        NVL(TRIM(c.PJ_FUNCTION), '(NA)') AS PJ_FUNCTION,
        NVL(TRIM(c.PJ_TYPE), '(NA)') AS PJ_TYPE,
        NVL(TRIM(c.PRODUCTNAME), '(NA)') AS PRODUCTNAME,
        NVL(TRIM(r.SPECNAME), '(NA)') AS SPECNAME,
        NVL(TRIM(r.LOSSREASONNAME), '(未填寫)') AS LOSSREASONNAME,
        NVL(TRIM(r.EQUIPMENTNAME), '(NA)') AS EQUIPMENTNAME,
        TRIM(r.REJECTCOMMENT) AS REJECTCOMMENT,
        NVL(r.REJECTQTY, 0) AS REJECT_QTY,
        NVL(r.STANDBYQTY, 0) AS STANDBY_QTY,
        NVL(r.QTYTOPROCESS, 0) AS QTYTOPROCESS_QTY,
        NVL(r.INPROCESSQTY, 0) AS INPROCESS_QTY,
        NVL(r.PROCESSEDQTY, 0) AS PROCESSED_QTY,
        NVL(r.REJECTQTY, 0)
          + NVL(r.STANDBYQTY, 0)
          + NVL(r.QTYTOPROCESS, 0)
          + NVL(r.INPROCESSQTY, 0)
          + NVL(r.PROCESSEDQTY, 0) AS REJECT_TOTAL_QTY,
        NVL(r.DEFECTQTY, 0) AS DEFECT_QTY,
        r.TXNDATE AS TXN_TIME,
        r.TXNDATE,
        TRUNC(r.TXNDATE) AS TXN_DAY
    FROM wip_lots w
    JOIN DWH.DW_MES_LOTREJECTHISTORY r ON r.CONTAINERID = w.CONTAINERID
    LEFT JOIN DWH.DW_MES_CONTAINER c ON c.CONTAINERID = r.CONTAINERID
    LEFT JOIN spec_map sm ON sm.SPEC = TRIM(r.SPECNAME)
)
SELECT *
FROM reject_data
ORDER BY
    TXN_DAY DESC,
    WORKCENTERSEQUENCE_GROUP ASC,
    WORKCENTERNAME ASC,
    REJECT_TOTAL_QTY DESC,
    CONTAINERNAME ASC,
    TXNDATE DESC
