-- Optimized: query_tool/lot_rejects
-- Change: Wrapped in subquery so ORDER BY uses projected alias REJECT_TOTAL_QTY
--         instead of re-computing the 5-field NVL sum expression

WITH spec_map AS (
    SELECT
        SPEC,
        MIN(WORK_CENTER) KEEP (
            DENSE_RANK FIRST ORDER BY WORKCENTERSEQUENCE_GROUP
        ) AS WORK_CENTER,
        MIN(WORK_CENTER_GROUP) KEEP (
            DENSE_RANK FIRST ORDER BY WORKCENTERSEQUENCE_GROUP
        ) AS WORKCENTER_GROUP,
        MIN(WORKCENTERSEQUENCE_GROUP) AS WORKCENTERSEQUENCE_GROUP
    FROM DWH.DW_MES_SPEC_WORKCENTER_V
    WHERE SPEC IS NOT NULL
    GROUP BY SPEC
),
reject_data AS (
    SELECT
        r.CONTAINERID,
        NVL(TRIM(c.CONTAINERNAME), TRIM(r.CONTAINERID)) AS CONTAINERNAME,
        NVL(TRIM(sm.WORK_CENTER), NVL(TRIM(r.WORKCENTERNAME), '(NA)')) AS WORKCENTERNAME,
        NVL(TRIM(sm.WORKCENTER_GROUP), NVL(TRIM(r.WORKCENTERNAME), '(NA)')) AS WORKCENTER_GROUP,
        NVL(sm.WORKCENTERSEQUENCE_GROUP, 999) AS WORKCENTERSEQUENCE_GROUP,
        NVL(TRIM(c.PRODUCTLINENAME), '(NA)') AS PRODUCTLINENAME,
        NVL(TRIM(c.PJ_FUNCTION), '(NA)') AS PJ_FUNCTION,
        NVL(TRIM(c.PJ_TYPE), '(NA)') AS PJ_TYPE,
        NVL(TRIM(c.PRODUCTNAME), '(NA)') AS PRODUCTNAME,
        NVL(TRIM(r.SPECNAME), '(NA)') AS SPECNAME,
        NVL(TRIM(r.LOSSREASONNAME), '(未填寫)') AS LOSSREASONNAME,
        NVL(TRIM(r.EQUIPMENTNAME), '(NA)') AS EQUIPMENTNAME,
        TRIM(r.REJECTCOMMENT) AS REJECTCOMMENT,
        NVL(r.REJECTQTY, 0) AS REJECT_QTY,
        NVL(r.STANDBYQTY, 0) AS STANDBY_QTY,
        NVL(r.QTYTOPROCESS, 0) AS QTYTOPROCESS_QTY,
        NVL(r.INPROCESSQTY, 0) AS INPROCESS_QTY,
        NVL(r.PROCESSEDQTY, 0) AS PROCESSED_QTY,
        NVL(r.REJECTQTY, 0)
          + NVL(r.STANDBYQTY, 0)
          + NVL(r.QTYTOPROCESS, 0)
          + NVL(r.INPROCESSQTY, 0)
          + NVL(r.PROCESSEDQTY, 0) AS REJECT_TOTAL_QTY,
        NVL(r.DEFECTQTY, 0) AS DEFECT_QTY,
        r.TXNDATE AS TXN_TIME,
        r.TXNDATE,
        TRUNC(r.TXNDATE) AS TXN_DAY
    FROM DWH.DW_MES_LOTREJECTHISTORY r
    LEFT JOIN DWH.DW_MES_CONTAINER c
      ON c.CONTAINERID = r.CONTAINERID
    LEFT JOIN spec_map sm
      ON sm.SPEC = TRIM(r.SPECNAME)
    WHERE r.CONTAINERID = :container_id
)
SELECT *
FROM reject_data
ORDER BY
    TXN_DAY DESC,
    WORKCENTERSEQUENCE_GROUP ASC,
    WORKCENTERNAME ASC,
    REJECT_TOTAL_QTY DESC,
    CONTAINERNAME ASC,
    TXNDATE DESC
